### PR TITLE
1.18.2: Fix DashLoader incompatibility

### PR DESCRIPTION
**Pull request by Dragon-Seeker**
Heard you were doing a re-write or 2.0 where this will get fixed but at least this will patch the problem temporary.

TLDR: Alpha says hi

### CODE REVIEW

**Comment by Shadowrs** [comment]
bump @PepperCode1 can we have a merge and push to modrinth? Then dashloader can be added back to the popular All Of Fabric 5 modpack

**Comment by PepperCode1** [comment]
These changes have already been made locally as part of 2.0.0 and will not be getting a separate release.

**Comment by Dragon-Seeker** [comment]
When will the release of 2.0.0 be? Not trying to rush anything but a simple version increment to fix mod incompatibly like this isn't too much of a head ache if the major update isn't ready anytime soon.

**Comment by lxly9** [comment]
Umm dashloader works just fine with the new continuity beta for me, in which way are they incompatible?

**Comment by Dragon-Seeker** [comment]
> Umm dashloader works just fine with the new continuity beta for me, in which way are they incompatible?

This is referring to the current stable version/branch.

**Comment by PepperCode1** [comment]
The relevant change was included in commit 8b36239ce0e5c2df7c672a12fdfebcf11e5354f0. A release for 2.0.0 will be made soon.

**Pull request closed without merging**
