### PR TITLE
Port to 1.21.3

### PR DESCRIPTION
**Pull request by embeddedt**
Not very satisfied with the solution I used for storing the `ModelWrappingHandler` (stored it on `ModelBaker`, and added a passthrough implementation to `BakerImpl`). Everything else is pretty straightforward.

Ported this mostly for my own use; feel free to close if you've already done the work, I won't be offended.

### CODE REVIEW

**Comment by Lolothepro** [comment]
For your information, I think Pepper said that port 1.21.3 should no longer accept invalid characters, like OptiFIne
see: https://github.com/sp614x/optifine/issues/7773

**Comment by VitaminTree** [comment]
I tried out this build in 1.21.3. Connected textures work fine, however emissive textures cause a game crash. Turning the setting off works as a bypass to the crash.

**Comment by embeddedt** [comment]
Which resource pack did you use to test that? I had tried a basic emissive ores pack before making the PR and it seemed to work fine...

**Comment by VitaminTree** [comment]
My apologies, I hadn't thoroughly checked my mod folder and was still running Sodium with an unsupported version of Indium. I tested it without those and it seems to work fine. Again, sorry for the inconvenience.

**Comment by pikesthefish** [comment]
> port 1.21.3 should no longer accept invalid characters

Where do you see invalid characters?

**Comment by AimzUnknown** [comment]
how do i download this?
Does it work without indium now?

**Comment by Nilsson321** [comment]
ETA?

**Comment by megabyte6** [comment]
@VitaminTree @AimzUnknown it looks like Indium isn't required anymore since Sodium says they support the Fabric Rendering API out of the box in the [changelogs](https://modrinth.com/mod/sodium/changelog).

@AimzUnknown they probably built it themselves to test. You'd have to build the `jar` if you want a compiled version.

**Comment by PepperCode1** [comment]
The initial port was completed in 1b31e2b.

**Pull request closed without merging**
